import { Opportunity, Organization, UserProfile } from './types/database';

export const MOCK_ORGANIZATION: Organization = {
  id: 'org-krow-community',
  owner_id: 'user-organizer-1',
  name: 'Krow Community Action',
  description: 'Empowering local neighborhoods through sustainable environmental and community support initiatives.',
  logo_url: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=150&auto=format&fit=crop&q=80',
  banner_url: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=1200&auto=format&fit=crop&q=80',
  location: 'Toronto, Ontario, Canada',
  created_at: new Date().toISOString(),
};

export const MOCK_VOLUNTEER: UserProfile = {
  id: 'vol-user-1',
  email: 'alex.volunteer@krow.org',
  role: 'volunteer',
  name: 'Alex Mercer',
  age: 22,
  country: 'Canada',
  province: 'Ontario',
  city: 'Toronto',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  account_mode: 'myself',
  created_at: new Date().toISOString(),
};

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-1',
    organization_id: 'org-krow-community',
    title: 'High Park Tree Planting & Urban Forestry',
    description: 'Join us for a morning of restoring native tree species in High Park. Gloves, shovels, and refreshments provided for all volunteers.',
    banner_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop&q=80',
    date: '2026-08-15',
    start_time: '09:00',
    end_time: '13:00',
    location: 'High Park, Toronto, ON',
    minimum_age: 14,
    max_volunteers: 25,
    requirements: 'Wear sturdy closed-toe boots and bring a reusable water bottle.',
    parking_info: 'Free parking at Grenadier Cafe lot.',
    accessibility_notes: 'Wheelchair accessible paved paths available near main site.',
    contact_email: 'volunteer@krowcommunity.org',
    contact_phone: '+1 (416) 555-0192',
    created_at: '2026-08-01T10:00:00Z',
    organization: MOCK_ORGANIZATION,
    registrations_count: 18,
    is_registered: true,
  },
  {
    id: 'opp-2',
    organization_id: 'org-krow-community',
    title: 'Downtown Youth Food Bank Distribution',
    description: 'Help assemble, organize, and pack nutritious food hampers for local families in need across Toronto.',
    banner_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&auto=format&fit=crop&q=80',
    date: '2026-08-18',
    start_time: '14:00',
    end_time: '18:00',
    location: '450 Yonge St, Toronto, ON',
    minimum_age: 16,
    max_volunteers: 15,
    requirements: 'Friendly attitude and ability to lift 10kg packages.',
    parking_info: 'Underground paid parking available.',
    accessibility_notes: 'Fully accessible facility with elevators.',
    contact_email: 'foodbank@krowcommunity.org',
    contact_phone: '+1 (416) 555-0841',
    created_at: '2026-08-02T12:00:00Z',
    organization: MOCK_ORGANIZATION,
    registrations_count: 12,
    is_registered: false,
  },
  {
    id: 'opp-3',
    organization_id: 'org-krow-community',
    title: 'Ottawa River Shoreline Clean-up Drive',
    description: 'Protect local wildlife habitats by removing debris and microplastics along the Ottawa riverfront trail.',
    banner_url: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=800&auto=format&fit=crop&q=80',
    date: '2026-08-22',
    start_time: '10:00',
    end_time: '14:00',
    location: 'Britannia Park, Ottawa, ON',
    minimum_age: 12,
    max_volunteers: 30,
    requirements: 'Sun protection, hat, and outdoor work attire.',
    parking_info: 'Free parking on-site.',
    accessibility_notes: 'Paved trail portions accessible.',
    contact_email: 'ottawa@krowcommunity.org',
    contact_phone: '+1 (613) 555-0177',
    created_at: '2026-08-03T09:00:00Z',
    organization: {
      ...MOCK_ORGANIZATION,
      name: 'Capital EcoGuardians',
      location: 'Ottawa, Ontario',
    },
    registrations_count: 22,
    is_registered: false,
  },
  {
    id: 'opp-4',
    organization_id: 'org-krow-community',
    title: 'California Tech Mentor for High Schoolers',
    description: 'Mentor aspiring young coders and designers in intro Python & UI workshop series.',
    banner_url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format&fit=crop&q=80',
    date: '2026-08-25',
    start_time: '15:30',
    end_time: '18:00',
    location: 'San Francisco Public Library, CA',
    minimum_age: 18,
    max_volunteers: 10,
    requirements: 'Basic programming knowledge in Python or JavaScript.',
    parking_info: 'BART accessible (Civic Center Station).',
    accessibility_notes: 'ADA compliant venue.',
    contact_email: 'sftech@krowcommunity.org',
    contact_phone: '+1 (415) 555-0922',
    created_at: '2026-08-04T11:00:00Z',
    organization: {
      ...MOCK_ORGANIZATION,
      name: 'SF Youth Tech Alliance',
      location: 'San Francisco, California',
    },
    registrations_count: 6,
    is_registered: false,
  }
];
